package fr.ifpen.synergreen.domain.enumeration;

/**
 * The DataType enumeration.
 */
public enum DataType {
    POWER,
    ENERGY,
    SOC,
    CONSOMMATION,
    CONSOMMATION_FROM_GRID,
    CONSOMMATION_FROM_PRODUCTION,
    CONSOMMATION_FROM_STORAGE,
    D_CONS,
    D_PROD,
    D_STRG,
    PRODUCTION,
    PRODUCTION_TO_SELL,
    PRODUCTION_SELF_CONSUMED,
    PRODUCTION_CONSUMED_BY_BATTERIES,
    STORAGE,
    STORAGE_CONSOMMATION_FROM_GRID,
    STORAGE_PRODUCTION_CONSUMED_BY_CONSUMERS, //AS CONSO FROM BATT
    PRIX_CONS,
    PRIX_PROD_SELL
}
