synergreen/
    __init__.py
    battery_management/
        __init__.py
        DataPrepare.py
        optimize.py
        ProblemOPEX.py
        BatteryManagementScript.py
    optimization/
        __init__.py
